export const UPLOAD_FILE_START = "UPLOAD_FILE_START"
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS"
export const UPLOAD_FILE_FAIL = "UPLOAD_FILE_FAIL"

export const CONTACT_ID = "CONTACT_ID"

export const PHONE_NUMBER = "PHONE_NUMBER"

export const SEND_MESSAGE_START = "SEND_MESSAGE_START"
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS"
export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL"

